INSERT INTO SUBSCRIBERS VALUES ( NULL,'Sergey' );
INSERT INTO SUBSCRIBERS VALUES ( NULL,'Dmitry' );
INSERT INTO SUBSCRIBERS VALUES ( NULL, 'Loshara' );
INSERT INTO SUBSCRIBERS VALUES ( NULL, 'Banana' );
INSERT INTO SUBSCRIBERS VALUES ( NULL, 'Jack' );
INSERT INTO SUBSCRIBERS VALUES ( NULL, 'Blackjack' );