INSERT INTO PERIODCAL_TO_SUBSCRIBER values (1, 1);
INSERT INTO PERIODCAL_TO_SUBSCRIBER values (3, 1);
INSERT INTO PERIODCAL_TO_SUBSCRIBER values (2, 1);
INSERT INTO PERIODCAL_TO_SUBSCRIBER values (4, 1);
INSERT INTO PERIODCAL_TO_SUBSCRIBER values (4, 2);